== 'Apping up' de Triathlon Sport
_v 0.1 Oktober 2017_

=== Korte opdrachtsomschrijving
Realiseer een web en/of mobiele app voor weergave van de evenementenkalender van de Nederlandse Triathlon Bond (NTB).
Breidt deze uit met gebruikersvriendelijke functionaliteiten om entree tot de sport laagdrempeliger te maken of de veiligheid bij evenementen te verhogen.
Voor laagdrempeliger maken gebruik je gamification principes en het koppelen van online/offline belevin, voor de veiligheid voeg je communicatiemogelijkheid toe tussen devices (apps) en admins (desktop/web app/PWA).

_De Opdrachtgever is de Nederlandse Triathlon Bond, met bondsbureau op Sportcentrum Papendal, Arnhem._

==== Verdere inhoud van dit document
Hieronder een opsplitsing in een aantal basisfunctionaliteiten (*A*), een uitbreiding hierop als dit vlot verloopt (*B*).
En ook twee mogelijke verdiepende fases die de complexiteit nog verhogen, of in het oog gehouden moeten worden voor toekomstige uitbreidbaarheid (*C* en *D*).
Uit C en D kan ook geshopt worden. Alle beschreven functionaliteiten zijn ook concept ter indicatie. De daadwerkelijke functionaliteit moet een team vaststellen in overleg met de organisatie over wenselijkheid en begeleiders ikv haalbaarheid.

Deze is afhankelijk van eigen voorkeur, vermogen en gewenste leerervaring van (leden van de) projectroep, maar ook van de wensen van de organisatie en mogelijkheden en eventuele verdere lopende ontwikkelingen bij de NTB.

Na deze concept functionaliteiten geeft dit document vooral algemene achtergrond voor de opdracht, zodat teamleden een beeld krijgen van de mogelijkheden, gebruikersgroep, etc.

=== Project A. Basis app
Enkele mogelijke functionaliteiten:

- Toon evenementen van een jaar, en sta toe te bladeren door jaren
- Geef gebruiker de mogelijkheid om interessante evenementen te markeren
- Toon per evenement de startseries
- Biedt voor nieuwe gebruikers ook achtergrondinformatie over de triathlon sport zoals gestandaardiseerd afstanden (sprint, OD, etc), sportvarianten, en de wedstrijdreglementen en gerelateerde info zoals informatie over stayeren, wetsuit gebruik en kledingvoorschriften
- Geef filter mogelijkheden in kalender (sportsoort, afstand, NK's, per regio)


=== Studenten
Gewenste student profielen: DABS, MDEP, MAD.

=== Docenten
Mogelijk begeleidende docenten: Nog te bepalen.

=== Checklist

[cols="4a, 1a"] 
|===

| *Item*
| *Ja/Nee*

| * Probleem is voldoende realistisch                                     
| Ja

| * Probleem is voldoende geschikt voor DAPS/MDEB/MAD studenten           
| Ja

| * Probleem kan is qua omvang voldoende voor 1 periode                   
| Nee

| * Inschatting globale niveau project,(zeer makkelijk 1…5 zeer moeilijk) 
|   2

|===

==== Project B. App data-invoer + uitbreiden koppeling
- Personaliseer de App met inlog mogelijkheid om de eigen sportbeleving en -vorderingen in kaart te houden (koppeling bv. Strava account, en totalen tonen, eigen PR's invoeren en tonen, delen via social media, kalenderfilter opslaan)
- Neem in de app informatie op over goede manier van doelen stellen
- Direct inschrijven via de app (evenementen waarvoor ingeschreven speciaal markeren).
- Apart aftelscherm naar (ingestelde) volgende geplande doelevenement (evt. ook op Apple Watch e.d.)
- Apart scherm met digitale variant van ledenpas toe voor identificatie/registratie bij wedstrijden (inclusief foto, foto upload, evt. QR code oid)
- Kalender werkt ook offline, en kan - als er netwerk of wifi is - via pull-to-refresh geupdatet worden met de laatste gegevens (laatste refresh datum zichtbaar tijdens pull)

=== Studenten
Gewenste student profielen: DABS, MDEP, MAD.

=== Docenten
Mogelijk begeleidende docenten: Nog te bepalen.

=== Checklist

[cols="4a, 1a"] 
|===

| *Item*
| *Ja/Nee*

| * Probleem is voldoende realistisch                                     
| Ja

| * Probleem is voldoende geschikt voor DAPS/MDEB/MAD studenten           
| [Ja/Nee]

| * Probleem kan is qua omvang voldoende voor 1 periode                   
| Ja

| * Inschatting globale niveau project,(zeer makkelijk 1…5 zeer moeilijk) 
|   3

|===

=== C. Verdiepende opdracht: gamification
Als verdiepende opdracht kan ook gekeken worden naar verdere mogelijkheden voor integratie van offline en online sportbeleving en gamification. Dit kan via koppeling en gebruik van app gegevens op de wedstrijddag.

A. Bijvoorbeeld aanmelding met app via Bluetooth token aanwezig op het wedstrijd terrein.
B. Nemen van een foto/selfie van aangemeld team gekoppeld aan aangemelde status en het direct verspreiden van foto+incheck bericht via social media accounts.
C. Koppeling aan uitslagensysteem(en) (zodat bv. naast zelf opgegeven PR's ook 'officiele' PR's in app komen).
D. Koppelen aan externe sportregistratie en/of planningssystemen (Strava, Endomundo, Trainingpeaks etc.)

=== Studenten
Gewenste student profielen: DABS, MDEP, MAD.

=== Docenten
Mogelijk begeleidende docenten: Nog te bepalen.

=== Checklist

[cols="4a, 1a"] 
|===

| *Item*
| *Ja/Nee*

| * Probleem is voldoende realistisch                                     
| Ja

| * Probleem is voldoende geschikt voor DAPS/MDEB/MAD studenten           
| [Ja/Nee]

| * Probleem kan is qua omvang voldoende voor 1 periode                   
| Ja

| * Inschatting globale niveau project,(zeer makkelijk 1…5 zeer moeilijk) 
|   5

|===

==== D. Verdiepende opdracht: Vrijwilligers en communicatie tbv de veiligheid
In het kader van de veiligheid zijn tot slot ook nog functionaliteiten te maken:

- versturen van berichten (push notificatie) naar alle deelnemers van een evenement
- aanmelden van vrijwilligers t.b.v. verzekering vooraf en vervolgens registreren tijdens de wedstrijd
- tijdens de wedstrijd versturen van berichten met algemene informatie of instructies maar ook kritieke instructies naar alle vrijwilligers in noodsituaties zoals onweer, ongeval, etc.

=== Studenten
Gewenste student profielen: DABS, MDEP, MAD.

=== Docenten
Mogelijk begeleidende docenten: Nog te bepalen.

=== Checklist

[cols="4a, 1a"] 
|===

| *Item*
| *Ja/Nee*

| * Probleem is voldoende realistisch                                     
| Ja

| * Probleem is voldoende geschikt voor DAPS/MDEB/MAD studenten           
| [Ja/Nee]

| * Probleem kan is qua omvang voldoende voor 1 periode                   
| Ja

| * Inschatting globale niveau project,(zeer makkelijk 1…5 zeer moeilijk) 
|   4

|===

<<<
=== Achtergrond/TL;DR

==== Triathlon: groeiende sport
Triathlon is een groeiende sport in Nederland. De Nederlandse Triathlon Bond behartigt sinds jaar en dag de belangen van multi duursporters. Dit zowel voor individuele sporters als verenigingen en ook via ondersteuning van wedstrijdorganisaties bij het opzetten en uitvoeren van evenementen (triathlons, duathlons, zwemlopen en in toenemende mate ook de offroad en andere varianten hiervan). De NTB wijst bijvoorbeeld ook nationale kampioenschappen toe. En was betrokken bij organisatie van het WK triathlon in Nederland dit jaar (2017).

Het aantal leden neemt toe. Achtergrond is de toenemende vrije tijd van Nederlanders, maar ook de mogelijkheid zelfstandig indelen trainingen t.o.v. bijvoorbeeld teamsporten die lastig te combineren is met steeds drukkere agenda's. Daarnaast is er ook een groeiende bewustwording dat hart- en vaatproblemen en andere welvaartsziektes andere leefgewoonten vragen als gezonder leven en meer te bewegen. 

==== Doelen stellen en gamification
Psychologisch onderzoek geeft aan dat algemene lange termijn doelen als 'gezond eten' en 'regelmatig bewegen' veel mensen niet aan kan zetten tot echte gedragsverandering ([marshmellow test](https://en.wikipedia.org/wiki/Stanford_marshmallow_experiment)).

Het tot doel stellen van deelname aan een 'race' is een steeds populairdere en ook effectievere manier om nieuwe gewoontes en leefwijze daadwerkelijk te realiseren. Een hele triathlon is de nieuwe marathon. Daarnaast biedt triathlon ook kortere afstanden, die door combinatie van 3 sporten nog steeds als echte uitdaging gelden. Het beoefenen van verschillende sport(vorm)en is ook gevarieerder en verkleint ook de kans op blessures t.o.v. de situatie dat je in dezelfde trainingsuren enkel bv. hardloopt of fietst. Als je goede voornemens stelt in het kader van toeleven/trainen naar een uitdagende race is de succes factor veel groter.

Ook neemt het aantal teamwedstrijden toe, waarbij je als team gezamelijk deelneemt. En er zijn competities over meerdere wedstrijden in een seizoen. Samen zorgden deze voor een explosieve groei over de afgelopen jaren van deze nog kleine maar groeiende sport.

Doel hierbij is wel het laagdrempelig te maken. Fanatieke triatleten doen de sport ook wel zonder app. Het image van de triathlonsport is krachtig, maar kan voor beginners ook een te hoge drempel blijken. Uiteindelijk gaat het om verbetering van de eigen prestatie. Een van de oorzaken van sportbeoefening de afgelopen jaar is wellicht ook de toenemende mogelijkheden om je sportbeleving en prestaties online te delen. Dit kan via reguliere social media, maar ook komen er steeds speciale sportregistratie apps (zie onder).

==== Bestaande systemen en wens
De Triathlon Bond biedt een link:http://ntbinschrijvingen.nl[online evenementenkalender] ook gekoppeld aan een link:https://mijn.triathlonbond.nl[online inschrijfsysteem]. Deze systemen zijn functioneel en in gebruik, maar echter inmiddels nogal gedateerd qua vormgeving en werkwijze. Ook onder NTB leden is het merendeel reeds lang gewend aan gebruik van moderne web intefaces van social media, maar ook aan apps, zoals moderne en vaak commerciele sportregistratie apps als Strava, Endomundo, Sports tracker, Trainingspeaks. Qua gebruikersinterface ligt de norm dus vrij hoog.

De NTB heeft al langere tijd de wens de kalender ook in een app vorm aan te bieden. Hierbij is ook de wens om in de app persoonlijke gegevens op te slaan, zoals de persoonlijke records over verschillende afstanden, de volgende doelwedstrijd. Op termijn kan er ook integratie zijn met genoemde online sportplatforms. Concurrentie met deze commerciele partijen is niet wenselijk/realistisch, maar enkelen van deze platforms bieden ook API's aan die win-win mogelijkheden geven.

Vanuit een groep IT vrijwilligers is bij de NTB recent ook een (RESTful) API ontwikkeld om in de toekomst meer gegevens te ontsluiten. De evenementen uit de kalender zijn hier bijvoorbeeld al op te vragen (zie https://api.triathlonbond.nl CORS en Swagger-enabled API voor direct testen in browser). Deze API en bestaande systemen zijn gerealiseerd in .NET. Er is een ook testomgeving. In het kader van proof of concepts staat het studenten vrij ook eigen platform te gebruiken (Micro Services architectuur). In verband met privacy zitten ledengegevens echter op private host (geen Cloud).

Het bestaande maar verouderde online inschrijfsysteem kan verder ontsloten worden om ook inschrijving via deze app mogelijk te maken. Er moet nog wel een User Interface ontworpen en App gemaakt worden. Een voorbeeld layout voor telefoon/tablet is al wel beschikbaar gesteld door een vrijwilliger (afgestudeerd HAN-CMD student).

Naast zulke concrete zaken moet er binnen de opdracht ook met beleid- en bondsmedewerkers afgestemd worden en evt. gebruikers onderzoek gedaan (Arnhem kent ook een Triathlon Vereniging (TVA), en Nederland grootste teamtriathlon vindt plaats in zwembad Klarenbeek (teamtriathlon.nl)).

==== Totaalbeleving
Om tot een totaalbeleving te komen is het ook zaak om rondom de wedstrijden aan te sluiten, zodat de online en offline samenkomen. Bijvoorbeeld registreren met je app bij een wedstrijd via een Bluetooth token. Maar ook het nemen van een (team)foto en versturen van berichten via reeds bestaande social media accounts van de teams, verenigingen en/of teamleden. Of mogelijkheid te carpoolen met mede sportliefhebbers uit je buurt.

De afgelopen jaren heeft met name de teamcompetitie een voortrekkersrol gespeeld via moderne websites en gebruik van social media. Doordat deze geheel door vrijwilligers gerund worden is er echter nog geen ruimte geweest voor complexere zaken zoals apps.

=== Opdrachtgever
De opdrachtgever is de Nederlandse Triathlon Bond. Contactpersoon is Christie Brouwer.
Techisch contactpersoon is Johan Maat voor infrastructurele zaken en Bart van der Wal voor eventuele uitbreiding van de rest API.

